name: Writeups
url: https://ndevtk.github.io/writeups
permalink: pretty
plugins:
  - jekyll-feed
collections:
  posts:
    output: true
feed:
  collections:
    posts:
      path: "rss.xml"
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
