/**
 * observatory-pins.js - the frozen day's DAY-PINNED numbers as
 * data, GENERATED by observatory-freeze.mjs (--pins-only reruns
 * just this file from the existing fixture). Scalars are exact;
 * [value, tolerance] pairs are asserted within their stated
 * physical noise scale by the reference's generic runner. The
 * generatedFor stamp must equal the fixture's FIXTURE_AT - the
 * reference refuses stale pins. Regenerate, READ THE DIFF, then
 * commit fixture and pins together: the review is where
 * run-then-pin's deliberateness now lives.
 */

export const DAY_PINS = {
  generatedFor: '2026-09-05T12:21Z',
  column: {
    invDT: [0, 0.05],
    invHM: 134,
    foldsBeach: 1,
    foldsAloft: 2,
    r0Arcmin: [25.30038746994851, 0.3],
    r0IsaArcmin: [32.99043696204497, 0.3],
    flatten: [2.388159012848769, 0.05],
    rimArcsec: [30.116285379871048, 8]
  },
  wet: {
    order: ['Phoenix', 'London', 'Singapore', 'San Diego', 'Bergen', 'Mumbai'],
    raining: ['Mumbai'],
    w: {
      Bergen: [0.8142857142857143, 0.03],
      London: [0.31714285714285717, 0.03],
      Mumbai: [0.9600000000000001, 0.03],
      Phoenix: [0.12000000000000001, 0.03],
      'San Diego': [0.64, 0.03],
      Singapore: [0.5685714285714286, 0.03]
    }
  },
  pol: {
    maxPure: [0.8699279700373292, 0.02]
  },
  meteors: {
    zhrNow: [0.0025529364259676023, 0.5],
    daysToPeak: [-23.299205762666638, 0.1],
    topCode: 'NUE',
    topShare: [0.029532030895047707, 0.03]
  },
  aurora: {
    rows: 149,
    latestGwN: 15,
    latestAt: '2026-09-05T12:20Z',
    ovP: [0.06, 0.02],
    ovLatDeg: 62,
    kpEst: [0, 0.01]
  },
  contrail: {
    l250TC: [-42, 0.5],
    l250Tlc: [-51.06361015977839, 0.2],
    l250Rhi: [0.10494117621275592, 0.01],
    formLoM: 13171,
    formHiM: 16491,
    issr: [[10145, [1.1244703499944904, 0.01]]],
    persistNull: true,
    acN: 1,
    acMaxAltM: [1478.28, 0.5],
    acInForm: 0,
    acInPersist: 0
  },
  leewave: {
    levels: 28,
    layerMMs: [6.145850002661892, 0.05],
    layerScalarMs: [6.611111111111111, 0.05],
    spotHM: 1978,
    spotLamM: [3269.6905578421515, 5]
  },
  tide: {
    amps: {
      M2: [0.5282727778223729, 0.01],
      S2: [0.26482824571285063, 0.01],
      N2: [0.11683428671294709, 0.01],
      K1: [0.34148791058716876, 0.01],
      O1: [0.25698284062606774, 0.01],
      M4: [0.0027922856593633623, 0.01]
    },
    rmsOutM: [0.09134397982832827, 0.01],
    latestResidM: [0.04766020784281613, 0.02],
    maxAbsOutM: [0.23626790620033816, 0.02],
    rM2: [0.974673021812496, 0.01],
    rO1: [1.2008543954489148, 0.02]
  },
  sats: {
    passes: 82,
    nakedEye: 51,
    darkHours: [10.383333333333333, 0.15],
    bestNorad: 25544,
    bestMag: [-4.2978406804711495, 0.1],
    bestElDeg: [69.39935386041245, 1],
    rbTop8: 5,
    issTonight: true
  },
  lehn: {
    eyeM: 450,
    distM: 90000,
    declined: false,
    rmsK: [1.0176603549219836, 0.25],
    dTretr: [-2.3412656249999997, 0.4],
    dTballoon: [-2.203544117647059, 0.3],
    probedTopM: [449.1650390625, 3]
  },
  flash: {
    rateArcsecS: [12.50078659535518, 0.05],
    beachType: 'textbook',
    beachS: [0.9101091359254416, 0.15],
    aloftType: 'inferior-mirage',
    aloftS: [1.232682537926456, 0.2],
    aloftWidth: [20.147601992475504, 12],
    aloftMagX: [1.498992167203663, 0.6],
    aloftAppArcmin: [-30.37515545299185, 1],
    ducts: 0
  },
  marine: {
    stability: 'unstable',
    dTairSeaK: [-2.099999999999998, 0.05],
    filmLapseKm: [-28.721049081179586, 3],
    filmDropK: [0.27284996627120606, 0.05],
    pierTopM: 100,
    joinM: 716,
    modelBand: [100, 716],
    clamped: false,
    skinK: [0.3741214657634514, 0.02],
    dTairSkinK: [-1.7258785342365464, 0.05],
    lwDnWm2: [342.42257409531027, 3],
    q0Wm2: [123.20730507202968, 3],
    dewSource: 'METAR KSAN (16 km)',
    lwSource:
      "modelled sky: Brunt on the pier's air + 0% cover from METAR KSAN",
    uMeasMs: 1.9,
    u10nMs: [2.1699152737201985, 0.05],
    u10Ms: [1.9768843289810538, 0.05],
    warmK: [0, 0.02],
    warmSurfaceK: [0, 0.02],
    warmDzM: [19, 0.5],
    warmSolarKwhM2: [0, 0.05],
    forms: 'coare36',
    k50: false,
    uStarMs: [0.0704706657187211, 0.003],
    hsbWm2: [6.26040508829288, 0.5],
    hlbWm2: [37.14909823973311, 1],
    tauNm2: [0.0056262203568772364, 0.002],
    residualClass: '0-3 m/s',
    warmSensorM: [4.529000000000001, 0.05]
  },
  lehnSea: {
    eyeM: 2,
    distM: null,
    declined: true
  },
  closure: null
};
