/**
 * observatory-pins.js - the frozen day's DAY-PINNED numbers as
 * data, GENERATED by observatory-freeze.mjs (--pins-only reruns
 * just this file from the existing fixture). Scalars are exact;
 * [value, tolerance] pairs are asserted within their stated
 * physical noise scale by the reference's generic runner. The
 * generatedFor stamp must equal the fixture's FIXTURE_AT - the
 * reference refuses stale pins. Regenerate, READ THE DIFF, then
 * commit fixture and pins together: the review is where
 * run-then-pin's deliberateness now lives.
 */

export const DAY_PINS = {
  generatedFor: '2026-08-09T20:53Z',
  column: {
    invDT: [8.7, 0.05],
    invHM: 878,
    foldsBeach: 0,
    foldsAloft: 1,
    r0Arcmin: [38.17017135105405, 0.3],
    r0IsaArcmin: [32.99043696204497, 0.3],
    flatten: [0.7005730595174965, 0.05],
    rimArcsec: [46.870870329097684, 8]
  },
  wet: {
    order: ['Phoenix', 'London', 'San Diego', 'Singapore', 'Bergen', 'Mumbai'],
    raining: ['Mumbai'],
    w: {
      Bergen: [0.9542857142857144, 0.03],
      London: [0.22285714285714286, 0.03],
      Mumbai: [0.9657142857142859, 0.03],
      Phoenix: [0.09714285714285716, 0.03],
      'San Diego': [0.6057142857142858, 0.03],
      Singapore: [0.6742857142857143, 0.03]
    }
  },
  pol: {
    maxPure: [0.874480734638003, 0.02]
  },
  meteors: {
    zhrNow: [28.929438208226316, 0.5],
    daysToPeak: [2.732518936833356, 0.1],
    topCode: 'PER',
    topShare: [0.3306408185245019, 0.03]
  },
  aurora: {
    rows: 258,
    latestGwN: 13,
    latestAt: '2026-08-09T21:25Z',
    ovP: [0.05, 0.02],
    ovLatDeg: 71,
    kpEst: [1.33, 0.01]
  },
  contrail: {
    l250TC: [-41.1, 0.5],
    l250Tlc: [-48.17926567727552, 0.2],
    l250Rhi: [0.9963815541864853, 0.01],
    formLoM: 12431,
    formHiM: 16578,
    issr: [
      [10769, [1.0972837448363952, 0.01]],
      [11470, [1.0791292323228823, 0.01]]
    ],
    persistNull: true,
    acN: 74,
    acMaxAltM: [8846.82, 0.5],
    acInForm: 0,
    acInPersist: 0
  },
  leewave: {
    levels: 29,
    layerMMs: [0.43390620717408956, 0.05],
    layerScalarMs: [3.4299999999999997, 0.05],
    spotHM: 1908,
    spotLamM: [656.8816066810133, 5]
  },
  tide: {
    amps: {
      M2: [0.5258554704710658, 0.01],
      S2: [0.20140377675714904, 0.01],
      N2: [0.13016608922794187, 0.01],
      K1: [0.42695555773427274, 0.01],
      O1: [0.2565490898978216, 0.01],
      M4: [0.003904767409875476, 0.01]
    },
    rmsOutM: [0.0749777107705048, 0.01],
    latestResidM: [0.006062785110163088, 0.02],
    maxAbsOutM: [-0.18860445423506422, 0.02],
    rM2: [0.970213045149568, 0.01],
    rO1: [1.1988275228870169, 0.02]
  },
  sats: {
    passes: 88,
    nakedEye: 56,
    darkHours: [9.516666666666667, 0.15],
    bestNorad: 28932,
    bestMag: [0.7900806355045955, 0.1],
    bestElDeg: [75.66604212274808, 1],
    rbTop8: 7,
    issTonight: false
  },
  flash: {
    rateArcsecS: [11.927113001831344, 0.05],
    beachType: 'textbook',
    beachS: [1.4631960203600975, 0.15],
    aloftType: 'mock-mirage',
    aloftS: [1.6537655645679004, 0.2],
    aloftWidth: [60.44280597742651, 12],
    aloftMagX: [3.9820387413723464, 0.6],
    aloftAppArcmin: [-21.86839016727958, 1],
    ducts: 0
  },
  closure: {
    globalRatio: [0.9739819539544845, 0.01],
    beamRatio: [1.1454677271244231, 0.02],
    diffuseRatio: [0.320199021876009, 0.02]
  }
};
