name: Spellcheck Action

on:
  workflow_run:
    workflows: ["Prettier action"]
      
jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # The checkout step
    - uses: actions/checkout@v4
    - uses: rojopolis/spellcheck-github-actions@v0
      name: Spellcheck
